### ISSUE TITLE
Separating baked files- with no extra header footer code. 

### ISSUE THREAD

**Issue by mshumaira** [gruntjs/grunt-docs#148]
I have used grunt bake plugin to generate static pages with common header and footer, whose code is written only once.  
My website pages are divided into diff folders. 
folderX-  Apage.html,Bpage.html
folderY- Cpage.html,Dpage.html
folderZ- Epage.html
sharedfolder- header.html, footer.html

dist (with header and footer code)- 
	which has follwing folders in it 
	folderX-  Apage.html,Bpage.html
	folderY- Cpage.html,Dpage.html
	folderZ- Epage.html
	index.html(file)
	
the navigaiton of  pages in folderX folderY and folderZ works fine . but for index.html it not working properly. 

for example header code for all the file contains 
![header](https://cloud.githubusercontent.com/assets/5453289/12166756/f8f96558-b549-11e5-9ecc-d90fecb37b78.PNG)

when i navigate from index.html page to lets say folderX>Apage.html error occurs and its because we are already in dist/ we need to go further down not out . 

Unfortunately, I have not figured out a clean solution to this without introducing multiple versions of header.html and footer.html. 
This is because the paths of the files (the CSS and JS dependencies and nav files ) are relative to the location of /dist/folderX lets say and when user navigates from folderX category to folderY category page we actually need to navigate across folders which can be done by first going one step back in directory and then going into the folderY and selecting that page. 
but For a page which is already one step back how should i navigate for that . 
  
I hope this issue makes sense.

**Comment by JKAussieSkater** [comment]
I believe you have reported this issue on the wrong software project.

This is `grunt-docs`, where we document how to use Grunt. We don't document for 3rd party plugins on `gruntjs/grunt-docs`.

Your issue is with a Grunt plugin ([grunt-bake](https://github.com/MathiasPaumgarten/grunt-bake)), you should report the issue on the developer's project, so that they can help you:

https://github.com/MathiasPaumgarten/grunt-bake/issues
