### ISSUE TITLE
Support HTTPS

### ISSUE THREAD

**Issue by bhubbard** [gruntjs/grunt-docs#182]
I would like to see gruntjs.com using HTTPS.

**Comment by XhmikosR** [comment]
@vladikoff we can use CloudFlare for starters without a redirect to HTTPS.

**Comment by steveoh** [comment]
I've been looking into this recently. Cloudflare is an insecure option but gives the affect of https. Since gruntjs is all public no passwords/accounts/etc it seems like a fine option. You can use the cloudflare flexible ssl feature with the free plan if you route all of your traffic through their name servers. GitLabs supports true https now while github pages does not. Hopefully github pages will support ssl in the near future.

**Comment by AurelioDeRosa** [comment]
I'm not sure where Grunt is deployed so my comment might not be relevant. Can we use [Let's encrypt](https://letsencrypt.org/) for HTTPS?

**Comment by XhmikosR** [comment]
I suggested CloudFlare because we don't need to change anything on the server side. I don't like CloudFlare for SSL, but it should help keep things moving.

/CC @vladikoff

**Comment by XhmikosR** [comment]
This is done now.
